version: '3'

services:
    redis:
        image: redis
    worker:
        image: localhost:5000/photos
        command: make worker-prod
        volumes:
          - local-photos:/photos/
        environment:
            - CELERY_HOST=redis
            - REDIS_HOST=redis
            - DJANGO_SETTINGS_MODULE=photos.settings.prod
            - PHOTOS_DB_NAME=photos
            - PHOTOS_DB_PORT=5432
            - PHOTOS_DB_HOST=$DOCKERHOST
            # Postgres convenience
            - PGHOST=$DOCKERHOST
            - PGDATABASE=$PHOTOS_DB_NAME
            - PGUSER=$PHOTOS_DB_USER
            - PGPASSWORD=$PHOTOS_DB_PASSWORD
            # Papertrail
            - PAPERTRAIL_HOSTNAME=MemoriesNinja
            - PAPERTRAIL_URL=$WHATSON_PAPERTRAIL_URL
            - PAPERTRAIL_PORT=$WHATSON_PAPERTRAIL_PORT
            # Pass-through
            - DJANGO_SECRET_KEY
            - PHOTOS_RAVEN_DSN
            - PHOTOS_DB_USER
            - PHOTOS_DB_PASSWORD
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
    web:
        image: localhost:5000/photos
        command: make web-prod
        ports:
            - 8000:8000
        volumes:
          - local-photos:/photos/
        environment:
            - CELERY_HOST=redis
            - REDIS_HOST=redis
            - DJANGO_SETTINGS_MODULE=photos.settings.prod
            - PHOTOS_DB_NAME=photos
            - PHOTOS_DB_PORT=5432
            - PHOTOS_DB_HOST=$DOCKERHOST
            # Postgres convenience
            - PGHOST=$DOCKERHOST
            - PGDATABASE=$PHOTOS_DB_NAME
            - PGUSER=$PHOTOS_DB_USER
            - PGPASSWORD=$PHOTOS_DB_PASSWORD
            # Papertrail
            - PAPERTRAIL_HOSTNAME=MemoriesNinja
            - PAPERTRAIL_URL=$WHATSON_PAPERTRAIL_URL
            - PAPERTRAIL_PORT=$WHATSON_PAPERTRAIL_PORT
            # Pass-through
            - DJANGO_SECRET_KEY
            - PHOTOS_RAVEN_DSN
            - PHOTOS_DB_USER
            - PHOTOS_DB_PASSWORD
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY

volumes:
    local-photos:
