version: "3"

services:
  # Django Q worker
  worker:
    image: mattsegal/photos:latest
    command: /app/scripts/worker/prod.sh
    volumes:
      - local-photos:/photos/
      - /var/run/postgresql:/app/postgres.sock

    env_file:
      - .env.prod

  # Django web
  web:
    image: mattsegal/photos:latest
    command: /app/scripts/web/prod.sh
    ports:
      - 8000:8000
    volumes:
      - local-photos:/photos/
      - /var/run/postgresql:/app/postgres.sock
    env_file:
      - .env.prod
volumes:
  local-photos:
