version: "3"

services:
  # Postgres database
  database:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Django-Q worker
  worker:
    image: photos:latest
    command: /app/scripts/worker/dev.sh
    volumes:
      - ../app:/app
      - local-photos:/photos/
    links:
      - database
    env_file:
      - ../env/.env.dev
  web:
    image: photos:latest
    command: /app/scripts/web/dev.sh
    ports:
      - 8000:8000
    volumes:
      - ../app:/app
      - local-photos:/photos/
    links:
      - database
      - worker
    env_file:
      - ../env/.env.dev

volumes:
  local-photos:
  postgres-data:
