# Generated by Django 2.0.2 on 2018-02-18 01:47

from django.db import migrations, models
import django.db.models.deletion
import photos.images


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnailed_at', models.DateTimeField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.ImageField(upload_to=photos.images.get_s3_key)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.Album')),
            ],
        ),
    ]
