# Generated by Django 2.1.4 on 2018-12-17 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_albumdownload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumdownload',
            name='count_downloads',
        ),
    ]
