# Generated by Django 3.0.8 on 2020-07-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_remove_albumdownload_count_downloads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumDownload',
        ),
    ]
