# Generated by Django 2.0.2 on 2018-02-25 11:03

import django.core.files.storage
from django.db import migrations, models
import photos.images


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='local_file',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/srv/photos'), upload_to=photos.images.get_local_filename),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=photos.images.get_s3_key),
        ),
    ]
