name: Backup
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout transcrypt
        uses: actions/checkout@v2
        with:
          repository: elasticdog/transcrypt
          path: transcrypt

      - name: Initialise transcrypt
        run: ./transcrypt/transcrypt -c aes-256-cbc -p '${{ secrets.TRANSCRYPT_PASSWORD }}' --yes

      - name: Run backup script
        run: ./infra/backup.sh
        shell: bash
