name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout transcrypt
        uses: actions/checkout@v2
        with:
          repository: elasticdog/transcrypt
          path: transcrypt

      - name: Initialise transcrypt
        run: ./transcrypt/transcrypt -c aes-256-cbc -p '${{ secrets.TRANSCRYPT_PASSWORD }}' --yes

      - name: Build container image
        run: docker build -t mattsegal/photos:latest -f docker/Dockerfile .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: mattsegal
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push container image
        run: docker push mattsegal/photos:latest
